products: 
  green_tea: 
    product_code: 'GR1'
    name: 'Green Tea'
    price: 3.11
  strawberries: 
    product_code: 'SR1'
    name: 'Strawberries'
    price: 5.00
  coffee: 
    product_code: 'CF1'
    name: 'Coffee'
    price: 11.23